// <auto-generated />
using System;
using DefenceDB.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DefenceDB.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260601103424_AddSeedData")]
    partial class AddSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DefenceDB.EL.Models.AppRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("DefenceDB.EL.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IconClass")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IconClass = "bi bi-rocket-takeoff",
                            Name = "Füzeler",
                            Slug = "fuzeler",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IconClass = "bi bi-airplane-engines",
                            Name = "Savaş Uçakları",
                            Slug = "savas-ucaklari",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IconClass = "bi bi-tsunami",
                            Name = "Savaş Gemileri",
                            Slug = "savas-gemileri",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IconClass = "bi bi-radar",
                            Name = "Radarlar",
                            Slug = "radarlar",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Hava-Hava Füzeleri",
                            ParentCategoryId = 1,
                            Slug = "hava-hava-fuzeleri",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Balistik Füzeler",
                            ParentCategoryId = 1,
                            Slug = "balistik-fuzeler",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Anti-Gemi Füzeleri",
                            ParentCategoryId = 1,
                            Slug = "anti-gemi-fuzeleri",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Seyir Füzeleri",
                            ParentCategoryId = 1,
                            Slug = "seyir-fuzeleri",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Anti-Radyasyon Füzeleri",
                            ParentCategoryId = 1,
                            Slug = "anti-radyasyon",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Hipersonik Süzülme Araçları",
                            ParentCategoryId = 1,
                            Slug = "hgv",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Avcı (Fighter)",
                            ParentCategoryId = 2,
                            Slug = "avci-ucaklari",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Bombardıman",
                            ParentCategoryId = 2,
                            Slug = "bombardiman",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Eğitim",
                            ParentCategoryId = 2,
                            Slug = "egitim",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Hücumbot",
                            ParentCategoryId = 3,
                            Slug = "hucumbot",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Korvet",
                            ParentCategoryId = 3,
                            Slug = "korvet",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Fırkateyn",
                            ParentCategoryId = 3,
                            Slug = "firkateyn",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Muhrip (Destroyer)",
                            ParentCategoryId = 3,
                            Slug = "muhrip",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Denizaltı",
                            ParentCategoryId = 3,
                            Slug = "denizalti",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Hava Savunma Radarları",
                            ParentCategoryId = 4,
                            Slug = "hava-savunma-radarlari",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Hava Radarları (Airborne)",
                            ParentCategoryId = 4,
                            Slug = "airborne-radarlar",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Deniz Radarları (Naval)",
                            ParentCategoryId = 4,
                            Slug = "deniz-radarlari",
                            SortOrder = 0
                        });
                });

            modelBuilder.Entity("DefenceDB.EL.Models.DefenseProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NatoReportingName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YearIntroduced")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("DefenseProducts", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("DefenceDB.EL.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMainImage")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("DefenceDB.EL.Models.ProductRelationship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RelationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SourceProductId")
                        .HasColumnType("int");

                    b.Property<int>("TargetProductId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SourceProductId");

                    b.HasIndex("TargetProductId");

                    b.ToTable("ProductRelationships");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.AirDefenseRadar", b =>
                {
                    b.HasBaseType("DefenceDB.EL.Models.DefenseProduct");

                    b.Property<double?>("MaxRangeKm")
                        .HasColumnType("float");

                    b.Property<string>("RadarType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TargetTrackingCapacity")
                        .HasColumnType("int");

                    b.ToTable("AirDefenseRadars", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 27,
                            CategoryId = 19,
                            Country = "ABD",
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Manufacturer = "Lockheed Martin",
                            Name = "AN/SPY-1",
                            Slug = "",
                            MaxRangeKm = 310.0,
                            RadarType = "PESA",
                            TargetTrackingCapacity = 100
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 19,
                            Country = "Türkiye",
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Manufacturer = "Aselsan",
                            Name = "Ers-Int (Erken İhbar)",
                            Slug = "",
                            MaxRangeKm = 600.0,
                            RadarType = "AESA",
                            TargetTrackingCapacity = 200
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 19,
                            Country = "ABD",
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Manufacturer = "Raytheon",
                            Name = "Patriot AN/MPQ-65",
                            Slug = "",
                            MaxRangeKm = 150.0,
                            RadarType = "AESA",
                            TargetTrackingCapacity = 100
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 19,
                            Country = "Rusya",
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Manufacturer = "Almaz-Antey",
                            Name = "S-400 91N6E",
                            Slug = "",
                            MaxRangeKm = 600.0,
                            RadarType = "AESA",
                            TargetTrackingCapacity = 300
                        });
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.AirToAirMissile", b =>
                {
                    b.HasBaseType("DefenceDB.EL.Models.DefenseProduct");

                    b.Property<string>("GuidanceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("MaxSpeedMach")
                        .HasColumnType("float");

                    b.Property<string>("RangeClass")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("AirToAirMissiles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 12,
                            CategoryId = 5,
                            Country = "ABD",
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Manufacturer = "Raytheon",
                            Name = "AIM-9 Sidewinder",
                            Slug = "",
                            GuidanceType = "Infrared (IR)",
                            MaxSpeedMach = 2.5,
                            RangeClass = "Kısa"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 5,
                            Country = "ABD",
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Manufacturer = "Raytheon",
                            Name = "AIM-120 AMRAAM",
                            Slug = "",
                            GuidanceType = "Aktif Radar",
                            MaxSpeedMach = 4.0,
                            RangeClass = "Görüş Ötesi (BVR)"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            Country = "Avrupa Birliği",
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Manufacturer = "MBDA",
                            Name = "Meteor",
                            Slug = "",
                            GuidanceType = "Aktif Radar",
                            MaxSpeedMach = 4.0,
                            RangeClass = "Görüş Ötesi (BVR)"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 5,
                            Country = "Almanya",
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Manufacturer = "Diehl Defence",
                            Name = "IRIS-T",
                            Slug = "",
                            GuidanceType = "Infrared (IR)",
                            MaxSpeedMach = 3.0,
                            RangeClass = "Kısa"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 5,
                            Country = "Türkiye",
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Manufacturer = "TÜBİTAK SAGE",
                            Name = "GÖKDOĞAN",
                            Slug = "",
                            GuidanceType = "Aktif Radar",
                            MaxSpeedMach = 4.0,
                            RangeClass = "Görüş Ötesi (BVR)"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 5,
                            Country = "Türkiye",
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Manufacturer = "TÜBİTAK SAGE",
                            Name = "BOZDOĞAN",
                            Slug = "",
                            GuidanceType = "Infrared (IR)",
                            MaxSpeedMach = 4.0,
                            RangeClass = "Kısa"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 5,
                            Country = "Rusya",
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Manufacturer = "Vympel",
                            Name = "R-77 (AA-12 Adder)",
                            Slug = "",
                            GuidanceType = "Aktif Radar",
                            MaxSpeedMach = 4.0,
                            RangeClass = "Görüş Ötesi (BVR)"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 5,
                            Country = "Rusya",
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Manufacturer = "Vympel",
                            Name = "R-73 (AA-11 Archer)",
                            Slug = "",
                            GuidanceType = "Infrared (IR)",
                            MaxSpeedMach = 2.5,
                            RangeClass = "Kısa"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 5,
                            Country = "Çin",
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Manufacturer = "CASC",
                            Name = "PL-15",
                            Slug = "",
                            GuidanceType = "Aktif Radar",
                            MaxSpeedMach = 4.5,
                            RangeClass = "Görüş Ötesi (BVR)"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 5,
                            Country = "Fransa",
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Manufacturer = "MBDA",
                            Name = "MICA",
                            Slug = "",
                            GuidanceType = "IR/RF",
                            MaxSpeedMach = 3.0,
                            RangeClass = "Orta"
                        });
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.AirborneRadar", b =>
                {
                    b.HasBaseType("DefenceDB.EL.Models.DefenseProduct");

                    b.Property<double?>("MaxRangeKm")
                        .HasColumnType("float");

                    b.Property<string>("RadarType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TargetTrackingCapacity")
                        .HasColumnType("int");

                    b.ToTable("AirborneRadars", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 22,
                            CategoryId = 20,
                            Country = "ABD",
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Manufacturer = "Northrop Grumman",
                            Name = "AN/APG-81",
                            Slug = "",
                            MaxRangeKm = 160.0,
                            RadarType = "AESA",
                            TargetTrackingCapacity = 23
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 20,
                            Country = "ABD",
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Manufacturer = "Northrop Grumman",
                            Name = "AN/APG-77",
                            Slug = "",
                            MaxRangeKm = 240.0,
                            RadarType = "AESA",
                            TargetTrackingCapacity = 100
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 20,
                            Country = "Avrupa Birliği",
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Manufacturer = "Euroradar",
                            Name = "Captor-E",
                            Slug = "",
                            MaxRangeKm = 200.0,
                            RadarType = "AESA",
                            TargetTrackingCapacity = 60
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 20,
                            Country = "Rusya",
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Manufacturer = "NIIP",
                            Name = "Irbis-E",
                            Slug = "",
                            MaxRangeKm = 400.0,
                            RadarType = "PESA",
                            TargetTrackingCapacity = 30
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 20,
                            Country = "Türkiye",
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Manufacturer = "Aselsan",
                            Name = "MURAD",
                            Slug = "",
                            MaxRangeKm = 150.0,
                            RadarType = "AESA",
                            TargetTrackingCapacity = 40
                        });
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.AntiRadiationMissile", b =>
                {
                    b.HasBaseType("DefenceDB.EL.Models.DefenseProduct");

                    b.Property<double?>("RangeKm")
                        .HasColumnType("float");

                    b.Property<string>("SeekerType")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("AntiRadiationMissiles", (string)null);
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.AntiShipMissile", b =>
                {
                    b.HasBaseType("DefenceDB.EL.Models.DefenseProduct");

                    b.Property<double?>("RangeKm")
                        .HasColumnType("float");

                    b.Property<bool>("SeaSkimming")
                        .HasColumnType("bit");

                    b.Property<string>("SpeedClass")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("AntiShipMissiles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 31,
                            CategoryId = 7,
                            Country = "ABD",
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Manufacturer = "Boeing",
                            Name = "Harpoon",
                            Slug = "",
                            RangeKm = 140.0,
                            SeaSkimming = true,
                            SpeedClass = "Subsonic"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 7,
                            Country = "Türkiye",
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Manufacturer = "Roketsan",
                            Name = "ATMACA",
                            Slug = "",
                            RangeKm = 220.0,
                            SeaSkimming = true,
                            SpeedClass = "Subsonic"
                        });
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.BallisticMissile", b =>
                {
                    b.HasBaseType("DefenceDB.EL.Models.DefenseProduct");

                    b.Property<bool>("HasMirv")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNuclearCapable")
                        .HasColumnType("bit");

                    b.Property<double?>("PayloadKg")
                        .HasColumnType("float");

                    b.Property<double?>("RangeKm")
                        .HasColumnType("float");

                    b.ToTable("BallisticMissiles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 33,
                            CategoryId = 6,
                            Country = "ABD",
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Manufacturer = "Lockheed Martin",
                            Name = "Trident II D5",
                            Slug = "",
                            HasMirv = true,
                            IsNuclearCapable = true,
                            PayloadKg = 2800.0,
                            RangeKm = 12000.0
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 6,
                            Country = "Türkiye",
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Manufacturer = "Roketsan",
                            Name = "TAYFUN",
                            Slug = "",
                            HasMirv = false,
                            IsNuclearCapable = false,
                            PayloadKg = 500.0,
                            RangeKm = 560.0
                        });
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.BomberAircraft", b =>
                {
                    b.HasBaseType("DefenceDB.EL.Models.DefenseProduct");

                    b.Property<double?>("CombatRadiusKm")
                        .HasColumnType("float");

                    b.Property<bool>("IsNuclearCapable")
                        .HasColumnType("bit");

                    b.Property<double?>("PayloadCapacityKg")
                        .HasColumnType("float");

                    b.ToTable("BomberAircrafts", (string)null);
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.Corvette", b =>
                {
                    b.HasBaseType("DefenceDB.EL.Models.DefenseProduct");

                    b.Property<double?>("DisplacementTons")
                        .HasColumnType("float");

                    b.Property<bool>("HasHelipad")
                        .HasColumnType("bit");

                    b.ToTable("Corvettes", (string)null);
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.CruiseMissile", b =>
                {
                    b.HasBaseType("DefenceDB.EL.Models.DefenseProduct");

                    b.Property<double?>("CepMeters")
                        .HasColumnType("float");

                    b.Property<double?>("RangeKm")
                        .HasColumnType("float");

                    b.ToTable("CruiseMissiles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 39,
                            CategoryId = 8,
                            Country = "ABD",
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Manufacturer = "Raytheon",
                            Name = "Tomahawk",
                            Slug = "",
                            CepMeters = 10.0,
                            RangeKm = 1600.0
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 8,
                            Country = "Türkiye",
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Manufacturer = "TÜBİTAK SAGE / Roketsan",
                            Name = "SOM",
                            Slug = "",
                            CepMeters = 5.0,
                            RangeKm = 250.0
                        });
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.Destroyer", b =>
                {
                    b.HasBaseType("DefenceDB.EL.Models.DefenseProduct");

                    b.Property<double?>("DisplacementTons")
                        .HasColumnType("float");

                    b.Property<string>("RadarSystemType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VlsCellsCount")
                        .HasColumnType("int");

                    b.ToTable("Destroyers", (string)null);
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.FastAttackCraft", b =>
                {
                    b.HasBaseType("DefenceDB.EL.Models.DefenseProduct");

                    b.Property<double?>("DisplacementTons")
                        .HasColumnType("float");

                    b.Property<double?>("MaxSpeedKnots")
                        .HasColumnType("float");

                    b.ToTable("FastAttackCrafts", (string)null);
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.FighterAircraft", b =>
                {
                    b.HasBaseType("DefenceDB.EL.Models.DefenseProduct");

                    b.Property<double?>("CombatRadiusKm")
                        .HasColumnType("float");

                    b.Property<string>("Generation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasAesaRadar")
                        .HasColumnType("bit");

                    b.Property<bool>("HasStealth")
                        .HasColumnType("bit");

                    b.ToTable("FighterAircrafts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 11,
                            Country = "ABD",
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Çok amaçlı 4. nesil savaş uçağı.",
                            IsActive = true,
                            Manufacturer = "Lockheed Martin",
                            Name = "F-16 Fighting Falcon",
                            Slug = "",
                            CombatRadiusKm = 550.0,
                            Generation = "4",
                            HasAesaRadar = true,
                            HasStealth = false
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 11,
                            Country = "ABD",
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "5. nesil çok amaçlı hayalet savaş uçağı.",
                            IsActive = true,
                            Manufacturer = "Lockheed Martin",
                            Name = "F-35 Lightning II",
                            Slug = "",
                            CombatRadiusKm = 1090.0,
                            Generation = "5",
                            HasAesaRadar = true,
                            HasStealth = true
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 11,
                            Country = "ABD",
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hava üstünlüğü sağlayan 5. nesil savaş uçağı.",
                            IsActive = true,
                            Manufacturer = "Lockheed Martin",
                            Name = "F-22 Raptor",
                            Slug = "",
                            CombatRadiusKm = 850.0,
                            Generation = "5",
                            HasAesaRadar = true,
                            HasStealth = true
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 11,
                            Country = "Türkiye",
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Milli Muharip Uçak (MMU). 5. nesil çok rollü savaş uçağı.",
                            IsActive = true,
                            Manufacturer = "TUSAŞ",
                            Name = "KAAN",
                            Slug = "",
                            CombatRadiusKm = 1100.0,
                            Generation = "5",
                            HasAesaRadar = true,
                            HasStealth = true
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 11,
                            Country = "Avrupa Birliği",
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Çift motorlu, delta kanatlı çok rollü savaş uçağı.",
                            IsActive = true,
                            Manufacturer = "Eurofighter Jagdflugzeug",
                            Name = "Eurofighter Typhoon",
                            Slug = "",
                            CombatRadiusKm = 1390.0,
                            Generation = "4.5",
                            HasAesaRadar = true,
                            HasStealth = false
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 11,
                            Country = "Fransa",
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Omnirole savaş uçağı.",
                            IsActive = true,
                            Manufacturer = "Dassault Aviation",
                            Name = "Dassault Rafale",
                            Slug = "",
                            CombatRadiusKm = 1850.0,
                            Generation = "4.5",
                            HasAesaRadar = true,
                            HasStealth = false
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 11,
                            Country = "Rusya",
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Rusya'nın 5. nesil savaş uçağı.",
                            IsActive = true,
                            Manufacturer = "Sukhoi",
                            Name = "Su-57",
                            Slug = "",
                            CombatRadiusKm = 1500.0,
                            Generation = "5",
                            HasAesaRadar = true,
                            HasStealth = true
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 11,
                            Country = "Rusya",
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gelişmiş 4++ nesil çok amaçlı savaş uçağı.",
                            IsActive = true,
                            Manufacturer = "Sukhoi",
                            Name = "Su-35",
                            Slug = "",
                            CombatRadiusKm = 1600.0,
                            Generation = "4.5",
                            HasAesaRadar = true,
                            HasStealth = false
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 11,
                            Country = "Çin",
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Çin'in 5. nesil ağır savaş uçağı.",
                            IsActive = true,
                            Manufacturer = "Chengdu",
                            Name = "J-20 Mighty Dragon",
                            Slug = "",
                            CombatRadiusKm = 2000.0,
                            Generation = "5",
                            HasAesaRadar = true,
                            HasStealth = true
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 11,
                            Country = "İsveç",
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hafif, tek motorlu çok amaçlı uçak.",
                            IsActive = true,
                            Manufacturer = "Saab",
                            Name = "JAS 39 Gripen",
                            Slug = "",
                            CombatRadiusKm = 800.0,
                            Generation = "4.5",
                            HasAesaRadar = true,
                            HasStealth = false
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 11,
                            Country = "ABD",
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "F-15'in modernize edilmiş en gelişmiş versiyonu.",
                            IsActive = true,
                            Manufacturer = "Boeing",
                            Name = "F-15EX Eagle II",
                            Slug = "",
                            CombatRadiusKm = 1270.0,
                            Generation = "4.5",
                            HasAesaRadar = true,
                            HasStealth = false
                        });
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.Frigate", b =>
                {
                    b.HasBaseType("DefenceDB.EL.Models.DefenseProduct");

                    b.Property<double?>("DisplacementTons")
                        .HasColumnType("float");

                    b.Property<int?>("VlsCellsCount")
                        .HasColumnType("int");

                    b.ToTable("Frigates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 35,
                            CategoryId = 16,
                            Country = "Türkiye",
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Manufacturer = "STM",
                            Name = "İstif Sınıfı (TCG İstanbul)",
                            Slug = "",
                            DisplacementTons = 3000.0,
                            VlsCellsCount = 16
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 16,
                            Country = "Fransa",
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Manufacturer = "Naval Group",
                            Name = "FREMM Sınıfı",
                            Slug = "",
                            DisplacementTons = 6000.0,
                            VlsCellsCount = 32
                        });
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.HypersonicGlideVehicle", b =>
                {
                    b.HasBaseType("DefenceDB.EL.Models.DefenseProduct");

                    b.Property<string>("CarrierPlatform")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("MaxSpeedMach")
                        .HasColumnType("float");

                    b.ToTable("HypersonicGlideVehicles", (string)null);
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.Minehunter", b =>
                {
                    b.HasBaseType("DefenceDB.EL.Models.DefenseProduct");

                    b.Property<double?>("DisplacementTons")
                        .HasColumnType("float");

                    b.Property<string>("SonarType")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Minehunters", (string)null);
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.NavalRadar", b =>
                {
                    b.HasBaseType("DefenceDB.EL.Models.DefenseProduct");

                    b.Property<double?>("MaxRangeKm")
                        .HasColumnType("float");

                    b.Property<string>("RadarType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScanType")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("NavalRadars", (string)null);
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.Submarine", b =>
                {
                    b.HasBaseType("DefenceDB.EL.Models.DefenseProduct");

                    b.Property<double?>("DisplacementTons")
                        .HasColumnType("float");

                    b.Property<double?>("MaxDepthMeters")
                        .HasColumnType("float");

                    b.Property<string>("PropulsionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TorpedoTubesCount")
                        .HasColumnType("int");

                    b.ToTable("Submarines", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 37,
                            CategoryId = 18,
                            Country = "ABD",
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Manufacturer = "General Dynamics",
                            Name = "Virginia Sınıfı",
                            Slug = "",
                            DisplacementTons = 7900.0,
                            MaxDepthMeters = 240.0,
                            PropulsionType = "Nükleer",
                            TorpedoTubesCount = 4
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 18,
                            Country = "Türkiye",
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Manufacturer = "Gölcük Tersanesi",
                            Name = "Reis Sınıfı (Tip 214TN)",
                            Slug = "",
                            DisplacementTons = 2010.0,
                            MaxDepthMeters = 400.0,
                            PropulsionType = "AIP (Hava Bağımsız)",
                            TorpedoTubesCount = 8
                        });
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.TrainerAircraft", b =>
                {
                    b.HasBaseType("DefenceDB.EL.Models.DefenseProduct");

                    b.Property<string>("EngineType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaxSeats")
                        .HasColumnType("int");

                    b.ToTable("TrainerAircrafts", (string)null);
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Category", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("DefenceDB.EL.Models.DefenseProduct", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DefenceDB.EL.Models.ProductImage", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.DefenseProduct", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DefenceDB.EL.Models.ProductRelationship", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.DefenseProduct", "SourceProduct")
                        .WithMany("SourceRelationships")
                        .HasForeignKey("SourceProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DefenceDB.EL.Models.DefenseProduct", "TargetProduct")
                        .WithMany("TargetRelationships")
                        .HasForeignKey("TargetProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceProduct");

                    b.Navigation("TargetProduct");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DefenceDB.EL.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.AirDefenseRadar", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.DefenseProduct", null)
                        .WithOne()
                        .HasForeignKey("DefenceDB.EL.Models.Products.AirDefenseRadar", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.AirToAirMissile", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.DefenseProduct", null)
                        .WithOne()
                        .HasForeignKey("DefenceDB.EL.Models.Products.AirToAirMissile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.AirborneRadar", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.DefenseProduct", null)
                        .WithOne()
                        .HasForeignKey("DefenceDB.EL.Models.Products.AirborneRadar", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.AntiRadiationMissile", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.DefenseProduct", null)
                        .WithOne()
                        .HasForeignKey("DefenceDB.EL.Models.Products.AntiRadiationMissile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.AntiShipMissile", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.DefenseProduct", null)
                        .WithOne()
                        .HasForeignKey("DefenceDB.EL.Models.Products.AntiShipMissile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.BallisticMissile", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.DefenseProduct", null)
                        .WithOne()
                        .HasForeignKey("DefenceDB.EL.Models.Products.BallisticMissile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.BomberAircraft", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.DefenseProduct", null)
                        .WithOne()
                        .HasForeignKey("DefenceDB.EL.Models.Products.BomberAircraft", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.Corvette", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.DefenseProduct", null)
                        .WithOne()
                        .HasForeignKey("DefenceDB.EL.Models.Products.Corvette", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.CruiseMissile", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.DefenseProduct", null)
                        .WithOne()
                        .HasForeignKey("DefenceDB.EL.Models.Products.CruiseMissile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.Destroyer", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.DefenseProduct", null)
                        .WithOne()
                        .HasForeignKey("DefenceDB.EL.Models.Products.Destroyer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.FastAttackCraft", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.DefenseProduct", null)
                        .WithOne()
                        .HasForeignKey("DefenceDB.EL.Models.Products.FastAttackCraft", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.FighterAircraft", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.DefenseProduct", null)
                        .WithOne()
                        .HasForeignKey("DefenceDB.EL.Models.Products.FighterAircraft", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.Frigate", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.DefenseProduct", null)
                        .WithOne()
                        .HasForeignKey("DefenceDB.EL.Models.Products.Frigate", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.HypersonicGlideVehicle", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.DefenseProduct", null)
                        .WithOne()
                        .HasForeignKey("DefenceDB.EL.Models.Products.HypersonicGlideVehicle", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.Minehunter", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.DefenseProduct", null)
                        .WithOne()
                        .HasForeignKey("DefenceDB.EL.Models.Products.Minehunter", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.NavalRadar", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.DefenseProduct", null)
                        .WithOne()
                        .HasForeignKey("DefenceDB.EL.Models.Products.NavalRadar", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.Submarine", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.DefenseProduct", null)
                        .WithOne()
                        .HasForeignKey("DefenceDB.EL.Models.Products.Submarine", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.TrainerAircraft", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.DefenseProduct", null)
                        .WithOne()
                        .HasForeignKey("DefenceDB.EL.Models.Products.TrainerAircraft", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("DefenceDB.EL.Models.DefenseProduct", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("SourceRelationships");

                    b.Navigation("TargetRelationships");
                });
#pragma warning restore 612, 618
        }
    }
}
