// <auto-generated />
using System;
using DefenceDB.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DefenceDB.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260531233709_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DefenceDB.EL.Models.AppRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("DefenceDB.EL.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IconClass")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("DefenceDB.EL.Models.DefenseProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NatoReportingName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YearIntroduced")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("DefenseProducts", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("DefenceDB.EL.Models.ProductRelationship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RelationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SourceProductId")
                        .HasColumnType("int");

                    b.Property<int>("TargetProductId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SourceProductId");

                    b.HasIndex("TargetProductId");

                    b.ToTable("ProductRelationships");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.AirDefenseRadar", b =>
                {
                    b.HasBaseType("DefenceDB.EL.Models.DefenseProduct");

                    b.Property<double?>("MaxRangeKm")
                        .HasColumnType("float");

                    b.Property<string>("RadarType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TargetTrackingCapacity")
                        .HasColumnType("int");

                    b.ToTable("AirDefenseRadars", (string)null);
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.AirToAirMissile", b =>
                {
                    b.HasBaseType("DefenceDB.EL.Models.DefenseProduct");

                    b.Property<string>("GuidanceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("MaxSpeedMach")
                        .HasColumnType("float");

                    b.Property<string>("RangeClass")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("AirToAirMissiles", (string)null);
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.AirborneRadar", b =>
                {
                    b.HasBaseType("DefenceDB.EL.Models.DefenseProduct");

                    b.Property<double?>("MaxRangeKm")
                        .HasColumnType("float");

                    b.Property<string>("RadarType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TargetTrackingCapacity")
                        .HasColumnType("int");

                    b.ToTable("AirborneRadars", (string)null);
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.AntiRadiationMissile", b =>
                {
                    b.HasBaseType("DefenceDB.EL.Models.DefenseProduct");

                    b.Property<double?>("RangeKm")
                        .HasColumnType("float");

                    b.Property<string>("SeekerType")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("AntiRadiationMissiles", (string)null);
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.AntiShipMissile", b =>
                {
                    b.HasBaseType("DefenceDB.EL.Models.DefenseProduct");

                    b.Property<double?>("RangeKm")
                        .HasColumnType("float");

                    b.Property<bool>("SeaSkimming")
                        .HasColumnType("bit");

                    b.Property<string>("SpeedClass")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("AntiShipMissiles", (string)null);
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.BallisticMissile", b =>
                {
                    b.HasBaseType("DefenceDB.EL.Models.DefenseProduct");

                    b.Property<bool>("HasMirv")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNuclearCapable")
                        .HasColumnType("bit");

                    b.Property<double?>("PayloadKg")
                        .HasColumnType("float");

                    b.Property<double?>("RangeKm")
                        .HasColumnType("float");

                    b.ToTable("BallisticMissiles", (string)null);
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.BomberAircraft", b =>
                {
                    b.HasBaseType("DefenceDB.EL.Models.DefenseProduct");

                    b.Property<double?>("CombatRadiusKm")
                        .HasColumnType("float");

                    b.Property<bool>("IsNuclearCapable")
                        .HasColumnType("bit");

                    b.Property<double?>("PayloadCapacityKg")
                        .HasColumnType("float");

                    b.ToTable("BomberAircrafts", (string)null);
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.Corvette", b =>
                {
                    b.HasBaseType("DefenceDB.EL.Models.DefenseProduct");

                    b.Property<double?>("DisplacementTons")
                        .HasColumnType("float");

                    b.Property<bool>("HasHelipad")
                        .HasColumnType("bit");

                    b.ToTable("Corvettes", (string)null);
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.CruiseMissile", b =>
                {
                    b.HasBaseType("DefenceDB.EL.Models.DefenseProduct");

                    b.Property<double?>("CepMeters")
                        .HasColumnType("float");

                    b.Property<double?>("RangeKm")
                        .HasColumnType("float");

                    b.ToTable("CruiseMissiles", (string)null);
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.Destroyer", b =>
                {
                    b.HasBaseType("DefenceDB.EL.Models.DefenseProduct");

                    b.Property<double?>("DisplacementTons")
                        .HasColumnType("float");

                    b.Property<string>("RadarSystemType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VlsCellsCount")
                        .HasColumnType("int");

                    b.ToTable("Destroyers", (string)null);
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.FastAttackCraft", b =>
                {
                    b.HasBaseType("DefenceDB.EL.Models.DefenseProduct");

                    b.Property<double?>("DisplacementTons")
                        .HasColumnType("float");

                    b.Property<double?>("MaxSpeedKnots")
                        .HasColumnType("float");

                    b.ToTable("FastAttackCrafts", (string)null);
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.FighterAircraft", b =>
                {
                    b.HasBaseType("DefenceDB.EL.Models.DefenseProduct");

                    b.Property<double?>("CombatRadiusKm")
                        .HasColumnType("float");

                    b.Property<string>("Generation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasAesaRadar")
                        .HasColumnType("bit");

                    b.Property<bool>("HasStealth")
                        .HasColumnType("bit");

                    b.ToTable("FighterAircrafts", (string)null);
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.Frigate", b =>
                {
                    b.HasBaseType("DefenceDB.EL.Models.DefenseProduct");

                    b.Property<double?>("DisplacementTons")
                        .HasColumnType("float");

                    b.Property<int?>("VlsCellsCount")
                        .HasColumnType("int");

                    b.ToTable("Frigates", (string)null);
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.HypersonicGlideVehicle", b =>
                {
                    b.HasBaseType("DefenceDB.EL.Models.DefenseProduct");

                    b.Property<string>("CarrierPlatform")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("MaxSpeedMach")
                        .HasColumnType("float");

                    b.ToTable("HypersonicGlideVehicles", (string)null);
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.Minehunter", b =>
                {
                    b.HasBaseType("DefenceDB.EL.Models.DefenseProduct");

                    b.Property<double?>("DisplacementTons")
                        .HasColumnType("float");

                    b.Property<string>("SonarType")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Minehunters", (string)null);
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.NavalRadar", b =>
                {
                    b.HasBaseType("DefenceDB.EL.Models.DefenseProduct");

                    b.Property<double?>("MaxRangeKm")
                        .HasColumnType("float");

                    b.Property<string>("RadarType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScanType")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("NavalRadars", (string)null);
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.Submarine", b =>
                {
                    b.HasBaseType("DefenceDB.EL.Models.DefenseProduct");

                    b.Property<double?>("DisplacementTons")
                        .HasColumnType("float");

                    b.Property<double?>("MaxDepthMeters")
                        .HasColumnType("float");

                    b.Property<string>("PropulsionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TorpedoTubesCount")
                        .HasColumnType("int");

                    b.ToTable("Submarines", (string)null);
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.TrainerAircraft", b =>
                {
                    b.HasBaseType("DefenceDB.EL.Models.DefenseProduct");

                    b.Property<string>("EngineType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaxSeats")
                        .HasColumnType("int");

                    b.ToTable("TrainerAircrafts", (string)null);
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Category", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("DefenceDB.EL.Models.DefenseProduct", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DefenceDB.EL.Models.ProductRelationship", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.DefenseProduct", "SourceProduct")
                        .WithMany("SourceRelationships")
                        .HasForeignKey("SourceProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DefenceDB.EL.Models.DefenseProduct", "TargetProduct")
                        .WithMany("TargetRelationships")
                        .HasForeignKey("TargetProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceProduct");

                    b.Navigation("TargetProduct");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DefenceDB.EL.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.AirDefenseRadar", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.DefenseProduct", null)
                        .WithOne()
                        .HasForeignKey("DefenceDB.EL.Models.Products.AirDefenseRadar", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.AirToAirMissile", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.DefenseProduct", null)
                        .WithOne()
                        .HasForeignKey("DefenceDB.EL.Models.Products.AirToAirMissile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.AirborneRadar", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.DefenseProduct", null)
                        .WithOne()
                        .HasForeignKey("DefenceDB.EL.Models.Products.AirborneRadar", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.AntiRadiationMissile", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.DefenseProduct", null)
                        .WithOne()
                        .HasForeignKey("DefenceDB.EL.Models.Products.AntiRadiationMissile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.AntiShipMissile", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.DefenseProduct", null)
                        .WithOne()
                        .HasForeignKey("DefenceDB.EL.Models.Products.AntiShipMissile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.BallisticMissile", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.DefenseProduct", null)
                        .WithOne()
                        .HasForeignKey("DefenceDB.EL.Models.Products.BallisticMissile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.BomberAircraft", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.DefenseProduct", null)
                        .WithOne()
                        .HasForeignKey("DefenceDB.EL.Models.Products.BomberAircraft", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.Corvette", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.DefenseProduct", null)
                        .WithOne()
                        .HasForeignKey("DefenceDB.EL.Models.Products.Corvette", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.CruiseMissile", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.DefenseProduct", null)
                        .WithOne()
                        .HasForeignKey("DefenceDB.EL.Models.Products.CruiseMissile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.Destroyer", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.DefenseProduct", null)
                        .WithOne()
                        .HasForeignKey("DefenceDB.EL.Models.Products.Destroyer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.FastAttackCraft", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.DefenseProduct", null)
                        .WithOne()
                        .HasForeignKey("DefenceDB.EL.Models.Products.FastAttackCraft", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.FighterAircraft", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.DefenseProduct", null)
                        .WithOne()
                        .HasForeignKey("DefenceDB.EL.Models.Products.FighterAircraft", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.Frigate", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.DefenseProduct", null)
                        .WithOne()
                        .HasForeignKey("DefenceDB.EL.Models.Products.Frigate", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.HypersonicGlideVehicle", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.DefenseProduct", null)
                        .WithOne()
                        .HasForeignKey("DefenceDB.EL.Models.Products.HypersonicGlideVehicle", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.Minehunter", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.DefenseProduct", null)
                        .WithOne()
                        .HasForeignKey("DefenceDB.EL.Models.Products.Minehunter", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.NavalRadar", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.DefenseProduct", null)
                        .WithOne()
                        .HasForeignKey("DefenceDB.EL.Models.Products.NavalRadar", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.Submarine", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.DefenseProduct", null)
                        .WithOne()
                        .HasForeignKey("DefenceDB.EL.Models.Products.Submarine", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Products.TrainerAircraft", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.DefenseProduct", null)
                        .WithOne()
                        .HasForeignKey("DefenceDB.EL.Models.Products.TrainerAircraft", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("DefenceDB.EL.Models.DefenseProduct", b =>
                {
                    b.Navigation("SourceRelationships");

                    b.Navigation("TargetRelationships");
                });
#pragma warning restore 612, 618
        }
    }
}
