// <auto-generated />
using System;
using DefenceDB.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DefenceDB.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260805141913_IncreaseTargetPathLength")]
    partial class IncreaseTargetPathLength
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DefenceDB.EL.Models.AppRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("DefenceDB.EL.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticleCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ContentMarkdown")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsShowcase")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.Property<string>("Summary")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ArticleCategoryId");

                    b.HasIndex("IsShowcase");

                    b.HasIndex("PublishedAt");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("DefenceDB.EL.Models.ArticleCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("ArticleCategories");
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IconClass")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsShowcase")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IconClass = "bi bi-rocket-takeoff",
                            IsShowcase = true,
                            Name = "Füzeler",
                            Slug = "fuzeler",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IconClass = "bi bi-airplane-engines",
                            IsShowcase = true,
                            Name = "Savaş Uçakları",
                            Slug = "savas-ucaklari",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IconClass = "bi bi-tsunami",
                            IsShowcase = true,
                            Name = "Savaş Gemileri",
                            Slug = "savas-gemileri",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IconClass = "bi bi-radar",
                            IsShowcase = true,
                            Name = "Radarlar",
                            Slug = "radarlar",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsShowcase = false,
                            Name = "Hava-Hava Füzeleri",
                            ParentCategoryId = 1,
                            Slug = "hava-hava-fuzeleri",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsShowcase = false,
                            Name = "Balistik Füzeler",
                            ParentCategoryId = 1,
                            Slug = "balistik-fuzeler",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsShowcase = false,
                            Name = "Anti-Gemi Füzeleri",
                            ParentCategoryId = 1,
                            Slug = "anti-gemi-fuzeleri",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsShowcase = false,
                            Name = "Seyir Füzeleri",
                            ParentCategoryId = 1,
                            Slug = "seyir-fuzeleri",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsShowcase = false,
                            Name = "Anti-Radyasyon Füzeleri",
                            ParentCategoryId = 1,
                            Slug = "anti-radyasyon",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsShowcase = false,
                            Name = "Hipersonik Süzülme Araçları",
                            ParentCategoryId = 1,
                            Slug = "hgv",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsShowcase = false,
                            Name = "Avcı (Fighter)",
                            ParentCategoryId = 2,
                            Slug = "avci-ucaklari",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsShowcase = false,
                            Name = "Bombardıman",
                            ParentCategoryId = 2,
                            Slug = "bombardiman",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsShowcase = false,
                            Name = "Eğitim",
                            ParentCategoryId = 2,
                            Slug = "egitim",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsShowcase = false,
                            Name = "Hava SOJ",
                            ParentCategoryId = 2,
                            Slug = "hava-soj-ucaklari",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsShowcase = false,
                            Name = "Askeri Kargo",
                            ParentCategoryId = 2,
                            Slug = "askeri-kargo-ucaklari",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsShowcase = false,
                            Name = "Deniz Karakol",
                            ParentCategoryId = 2,
                            Slug = "deniz-karakol-ucaklari",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsShowcase = false,
                            Name = "AWACS",
                            ParentCategoryId = 2,
                            Slug = "awacs-ucaklari",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsShowcase = false,
                            Name = "Hücumbot",
                            ParentCategoryId = 3,
                            Slug = "hucumbot",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsShowcase = false,
                            Name = "Korvet",
                            ParentCategoryId = 3,
                            Slug = "korvet",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsShowcase = false,
                            Name = "Fırkateyn",
                            ParentCategoryId = 3,
                            Slug = "firkateyn",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsShowcase = false,
                            Name = "Muhrip (Destroyer)",
                            ParentCategoryId = 3,
                            Slug = "muhrip",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsShowcase = false,
                            Name = "Denizaltı",
                            ParentCategoryId = 3,
                            Slug = "denizalti",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsShowcase = false,
                            Name = "Hava Savunma Radarları",
                            ParentCategoryId = 4,
                            Slug = "hava-savunma-radarlari",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsShowcase = false,
                            Name = "Hava Radarları (Airborne)",
                            ParentCategoryId = 4,
                            Slug = "airborne-radarlar",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsShowcase = false,
                            Name = "Deniz Radarları (Naval)",
                            ParentCategoryId = 4,
                            Slug = "deniz-radarlari",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IconClass = "bi bi-shield-shaded",
                            IsShowcase = false,
                            Name = "Kara Araçları",
                            Slug = "kara-araclari",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsShowcase = false,
                            Name = "Tanklar",
                            ParentCategoryId = 22,
                            Slug = "tanklar",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsShowcase = false,
                            Name = "Obüs Sistemleri",
                            ParentCategoryId = 22,
                            Slug = "obusler",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsShowcase = false,
                            Name = "Havan Sistemleri",
                            ParentCategoryId = 22,
                            Slug = "havan-sistemleri",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 51,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsShowcase = false,
                            Name = "Zırhlı Personel Taşıyıcılar (ZPT)",
                            ParentCategoryId = 22,
                            Slug = "zpt",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 52,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsShowcase = false,
                            Name = "Zırhlı Muharebe Araçları (ZMA)",
                            ParentCategoryId = 22,
                            Slug = "zma",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 53,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsShowcase = false,
                            Name = "Çok Namlulu Roketatar Sistemleri (ÇNRA)",
                            ParentCategoryId = 22,
                            Slug = "cnra",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IconClass = "bi bi-robot",
                            IsShowcase = true,
                            Name = "İnsansız Platformlar",
                            Slug = "insansiz-platformlar",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsShowcase = false,
                            Name = "İHA (UAV)",
                            ParentCategoryId = 23,
                            Slug = "iha-uav",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsShowcase = false,
                            Name = "İDA (USV)",
                            ParentCategoryId = 23,
                            Slug = "ida-usv",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsShowcase = false,
                            Name = "İKA (UGV)",
                            ParentCategoryId = 23,
                            Slug = "ika-ugv",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsShowcase = false,
                            Name = "Kamikaze İHA",
                            ParentCategoryId = 23,
                            Slug = "kamikaze-iha",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsShowcase = false,
                            Name = "Kamikaze İDA",
                            ParentCategoryId = 23,
                            Slug = "kamikaze-ida",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IconClass = "bi bi-gear-wide-connected",
                            IsShowcase = false,
                            Name = "Motor ve Güç Sistemleri",
                            Slug = "motor-ve-guc-sistemleri",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsShowcase = false,
                            Name = "Turbofan Motorlar",
                            ParentCategoryId = 30,
                            Slug = "turbofan-motorlar",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsShowcase = false,
                            Name = "Pistonlu/İçten Yanmalı Motorlar",
                            ParentCategoryId = 30,
                            Slug = "pistonlu-motorlar",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsShowcase = false,
                            Name = "Roket Motorları",
                            ParentCategoryId = 30,
                            Slug = "roket-motorlari",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsShowcase = false,
                            Name = "Elektrik ve Nükleer Güç",
                            ParentCategoryId = 30,
                            Slug = "elektrik-ve-nukleer-guc",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsShowcase = false,
                            Name = "Turbojet Motorlar",
                            ParentCategoryId = 30,
                            Slug = "turbojet-motorlar",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsShowcase = false,
                            Name = "Turboprop Motorlar",
                            ParentCategoryId = 30,
                            Slug = "turboprop-motorlar",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsShowcase = false,
                            Name = "Deniz Gaz Türbinleri",
                            ParentCategoryId = 30,
                            Slug = "deniz-gaz-turbinleri",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsShowcase = false,
                            Name = "Turboshaft Motorlar",
                            ParentCategoryId = 30,
                            Slug = "turboshaft-motorlar",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IconClass = "bi bi-shield-fill-check",
                            IsShowcase = true,
                            Name = "Hava Savunma Sistemleri",
                            Slug = "hava-savunma-sistemleri",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsShowcase = false,
                            Name = "Taşınabilir Hava Savunma Sistemleri (MANPADS)",
                            ParentCategoryId = 39,
                            Slug = "manpads",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsShowcase = false,
                            Name = "Yakın Savunma Silah Sistemleri (CIWS)",
                            ParentCategoryId = 39,
                            Slug = "ciws",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsShowcase = false,
                            Name = "Kundağı Motorlu Uçaksavar Topları (SPAAG)",
                            ParentCategoryId = 39,
                            Slug = "spaag",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsShowcase = false,
                            Name = "Hava ve Füze Savunma Sistemleri",
                            ParentCategoryId = 39,
                            Slug = "hava-ve-fuze-savunma-sistemleri",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 54,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IconClass = "bi bi-crosshair",
                            IsShowcase = false,
                            Name = "Piyade Silahları",
                            Slug = "piyade-silahlari",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = 55,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsShowcase = false,
                            Name = "Tabancalar",
                            ParentCategoryId = 54,
                            Slug = "tabancalar",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 56,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsShowcase = false,
                            Name = "Piyade Tüfekleri",
                            ParentCategoryId = 54,
                            Slug = "piyade-tufekleri",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 57,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsShowcase = false,
                            Name = "Makineli Tüfekler",
                            ParentCategoryId = 54,
                            Slug = "makineli-tufekler",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 58,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsShowcase = false,
                            Name = "Keskin Nişancı Tüfekleri",
                            ParentCategoryId = 54,
                            Slug = "keskin-nisanci-tufekleri",
                            SortOrder = 0
                        });
                });

            modelBuilder.Entity("DefenceDB.EL.Models.CategoryAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Options")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId", "Name")
                        .IsUnique();

                    b.ToTable("CategoryAttributes", (string)null);
                });

            modelBuilder.Entity("DefenceDB.EL.Models.DefenseProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsShowcase")
                        .HasColumnType("bit");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NatoReportingName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Specs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("YearIntroduced")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Country");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("IsActive", "IsShowcase");

                    b.ToTable("DefenseProducts", (string)null);
                });

            modelBuilder.Entity("DefenceDB.EL.Models.MascotSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LinksJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetPath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MascotSettings");
                });

            modelBuilder.Entity("DefenceDB.EL.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMainImage")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("DefenceDB.EL.Models.ProductRelationship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RelationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SourceProductId")
                        .HasColumnType("int");

                    b.Property<int>("TargetProductId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SourceProductId");

                    b.HasIndex("TargetProductId");

                    b.ToTable("ProductRelationships");
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Visitor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Browser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FirstVisitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VisitorHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("FirstVisitDate");

                    b.HasIndex("VisitorHash")
                        .IsUnique();

                    b.ToTable("Visitors");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Article", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.ArticleCategory", "ArticleCategory")
                        .WithMany("Articles")
                        .HasForeignKey("ArticleCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ArticleCategory");
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Category", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("DefenceDB.EL.Models.CategoryAttribute", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.Category", "Category")
                        .WithMany("Attributes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DefenceDB.EL.Models.DefenseProduct", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DefenceDB.EL.Models.ProductImage", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.DefenseProduct", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DefenceDB.EL.Models.ProductRelationship", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.DefenseProduct", "SourceProduct")
                        .WithMany("SourceRelationships")
                        .HasForeignKey("SourceProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DefenceDB.EL.Models.DefenseProduct", "TargetProduct")
                        .WithMany("TargetRelationships")
                        .HasForeignKey("TargetProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceProduct");

                    b.Navigation("TargetProduct");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DefenceDB.EL.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DefenceDB.EL.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DefenceDB.EL.Models.ArticleCategory", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("DefenceDB.EL.Models.Category", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("DefenceDB.EL.Models.DefenseProduct", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("SourceRelationships");

                    b.Navigation("TargetRelationships");
                });
#pragma warning restore 612, 618
        }
    }
}
